# Generated by Django 3.2.5 on 2022-02-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://carta.menu/assets/img/tmp/placeholder_restaurant.jpg', max_length=500),
        ),
    ]
